package arkhotech.multas;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@org.kie.api.definition.type.Label("multa")
public class Multa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   //@org.kie.api.definition.type.Label("Donde")
   private java.lang.String donde;
   //@org.kie.api.definition.type.Label("Monto")
   private java.lang.Integer monto;
   //@org.kie.api.definition.type.Label("Cuando")
   private java.util.Date cuando;
   //@org.kie.api.definition.type.Label("Infraccion")
   private java.lang.String infraccion;
   //@org.kie.api.definition.type.Label("Id")
   private java.lang.Integer id;

   public Multa()
   {
   }

   public java.lang.String getDonde()
   {
      return this.donde;
   }

   public void setDonde(java.lang.String donde)
   {
      this.donde = donde;
   }

   public java.lang.Integer getMonto()
   {
      return this.monto;
   }

   public void setMonto(java.lang.Integer monto)
   {
      this.monto = monto;
   }

   public java.util.Date getCuando()
   {
      return this.cuando;
   }

   public void setCuando(java.util.Date cuando)
   {
      this.cuando = cuando;
   }

   public java.lang.String getInfraccion()
   {
      return this.infraccion;
   }

   public void setInfraccion(java.lang.String infraccion)
   {
      this.infraccion = infraccion;
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public Multa(java.lang.String donde, java.lang.Integer monto,
         java.util.Date cuando, java.lang.String infraccion, java.lang.Integer id)
   {
      this.donde = donde;
      this.monto = monto;
      this.cuando = cuando;
      this.infraccion = infraccion;
      this.id = id;
   }

}