package arkhotech.multas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Multas implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   //@org.kie.api.definition.type.Label(value = "Multa")
   private arkhotech.multas.Multa multa;

   public Multas()
   {
   }

   public arkhotech.multas.Multa getMulta()
   {
      return this.multa;
   }

   public void setMulta(arkhotech.multas.Multa multa)
   {
      this.multa = multa;
   }

   public Multas(arkhotech.multas.Multa multa)
   {
      this.multa = multa;
   }

}