package arkhotech.multas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Opciones implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "item")
   private java.util.List<java.lang.String> item;

   public Opciones()
   {
   }

   public java.util.List<java.lang.String> getItem()
   {
      return this.item;
   }

   public void setItem(java.util.List<java.lang.String> item)
   {
      this.item = item;
   }

   public Opciones(java.util.List<java.lang.String> item)
   {
      this.item = item;
   }

}