package arkhotech.multas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResultMultas implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   // @org.kie.api.definition.type.Label(value = "Multas")
   private arkhotech.multas.Multas multas;

   public ResultMultas()
   {
   }

   public arkhotech.multas.Multas getMultas()
   {
      return this.multas;
   }

   public void setMultas(arkhotech.multas.Multas multas)
   {
      this.multas = multas;
   }

   public ResultMultas(arkhotech.multas.Multas multas)
   {
      this.multas = multas;
   }

}